Fix outputting select constructs for older kextractor versions
paulgazz/kmax pull request #162
Opened 2022-07-01 16:37 UTC by paulgazz

This uncomments the output of "select ..." lines in the kextract output, which is used by kismet to get the list of select constructs.  It was originally commented out in favor of "rev_dep ..." lines for kclause, which no longer needs the selects lines.

Fixes #161

2022-07-01 17:19 UTC, necipfazil commented
New kextractor versions had additional changes/fixes for kismet: https://github.com/paulgazz/kmax/commits/master/kextractors/kextractor-next-20200430/kextractor.c

We potentially need these changes in older kextractor versions as well.

2022-07-01 18:50 UTC, necipfazil commented
Tested the changes on Linux v4.16, which runs kextractor 4.12.8. kismet could not verify any of the alarms with the generated test cases.

This does not mean the changes in this PR are wrong. This should be due to the additional issues as outlined in https://github.com/paulgazz/kmax/issues/163

Content of output kismet_summary_x86_64.txt:

```
= Overall analysis =
Over 9284 select constructs, unmet dependency analysis resulted in: 9195 safe, 89 alarm.
0 of 89 alarms were successfully validated. Test cases couldn't verify the remaining 89 alarms.
The analysis was done in 2635.46 seconds.

= Timing results (seconds) =
Prefetch arch formulas     : 206.21
Identify constructs        : 3.86
Optimized SAT pass         : 67.42
Precise SAT pass           : 1885.27
Test case generation       : 439.06
Verification               : 33.65

= Per-stage results =

== Identification of select constructs & udd analysis through syntax ==
9284 select constructs identified in the architecture.
1920 select constructs were found udd safe through syntax analysis.
7364 select constructs were found udd alarm through syntax analysis.

== Optimized SAT pass ==
7364 select constructs with alarms from the previous stage were checked during optimized SAT pass.
5881 select constructs were found udd SAFE through optimized SAT pass.
1483 select constructs were found udd ALARM through optimized SAT pass.

== Precise SAT pass ==
1483 select constructs with alarms from the previous stage were checked during precise SAT pass.
1394 select constructs were found udd SAFE through precise SAT pass.
89 select constructs were found udd ALARM through precise SAT pass.

== Test case generation ==
89 select constructs with alarms from the previous stage were considered for test case generation, totaling 89 models with 89 due to generic and 0 due to SAT options.
89 test cases were generated.

== Verification ==
89 test cases were used during verification to verify alarms for 89 select constructs.
For 0 constructs, all test cases verified the alarm.
For 0 constructs, at least one test verified the alarm, thus, proving the existince of the udd.
For 89 constructs, none of the test cases verified the alarm, thus, false positive of kismet.
```

2022-07-15 04:50 UTC, necipfazil requested changes
LGTM.  However, please first merge https://github.com/paulgazz/kmax/pull/166, then this.

2022-07-15 16:54 UTC, paulgazz commented
#159's example on v4.16 x86_64 now works.

2022-07-16 17:41 UTC, necipfazil approved these changes

2022-07-17 12:13 UTC, merged