misc changes on kextractor, kclause, and klocalizer
paulgazz/kmax pull request #29
Opened 2020-10-06 10:38 UTC by necipfazil

Please see the commit messages for the details.

The changes do not affect the existing routines but provide additional options with new flags. 

One effect might be that the kclause file size increases (not by much, for example the increase is from 8.4M to 9.0M for x86_64) due to including more information regarding the individual select statements.

2020-10-06 12:50 UTC, necipfazil commented
Another note is that some issue in kmax was found, which was fixed locally and will later be fixed when the root cause is found.

The problem is that some symbols are written as `"FOO"` instead of `CONFIG_FOO`. See [fix_str_expr](https://github.com/paulgazz/kmax/pull/29/files#diff-8d62cac048e8a25600d27fadb8790cb1R379-R382) method for further details.

2020-10-07 02:36 UTC, paulgazz commented on kmax/klocalizer
> +    #elif len(kclause_to_try.keys()) > 1:
Is it now safe to try multiple architectures without a compilation unit?  Was this just an artificial limitation?

2020-10-07 02:42 UTC, paulgazz requested changes

2020-10-07 02:42 UTC, paulgazz commented on kmax/kclause
> +    # convert any "FOO" to CONFIG_FOO
Can you double-check whether the kextract output is producing a string, i.e., "FOO"?  This can happen when the FOO configuration option is used without being declared.  Otherwise, this change my cause incorrectness.

2020-10-07 02:42 UTC, paulgazz commented on kmax/kclause
> +    convert_str_expr_dict_to_smt2 = lambda str_expr_dict : dict((fix_str_expr(k), convert_str_expr_to_smtlib2(v)) for k,v in str_expr_dict.items())
Please check whether the config option in question is actually declared in the given architecture's Kconfig files.

2020-10-12 14:41 UTC, paulgazz approved these changes
The changes to kextract look okay to me.

2020-10-12 15:02 UTC, jeho-oh commented
I'm fine with the changes. I'll merge them with mine.

2020-10-12 15:43 UTC, paulgazz commented
> I'm fine with the changes. I'll merge them with mine.

Instead of closing this merge request, please contribute your changes to it.

2020-10-12 18:05 UTC, paulgazz commented on kextractors/kextractor-next-20200430/kextractor.c
> +        }
For completeness add a default case that says this is impossible due to the parser.  You could add an assert as well just to make sure.

2020-10-12 18:05 UTC, jeho-oh requested changes

2020-10-12 18:05 UTC, jeho-oh commented on kextractors/kextractor-next-20200430/kextractor.c
> +      if (sym_is_choice(sym)) {
It would be better to check if the choice is in the correct type instead of accepting any type.
 (sym_is_choice(sym) && (sym->type == S_BOOLEAN || sym->type == S_TRISTATE))

2020-10-12 19:15 UTC, jeho-oh commented on kextractors/kextractor-next-20200430/kextractor.c
> +      if (sym_is_choice(sym)) {
Nevermind. I checked such a case was blocked by syntax.

2020-10-12 19:16 UTC, jeho-oh approved these changes

2020-10-12 19:18 UTC, necipfazil commented on kmax/klocalizer
> +    #elif len(kclause_to_try.keys()) > 1:
I cannot see any reason why it wouldn't be safe to try multiple architectures without a compilation unit. Therefore, yes, I think it has been an artificial limitation.

Specifically, it was preventing to carry out scenarios where we want to find a satisfying configuration in the presence of user defined constraints, which can be an handy use case. (e.g., using `klocalizer --all --constraints-file-smt2=path/to/constraints.smt`)

2020-10-12 19:28 UTC, necipfazil commented on kextractors/kextractor-next-20200430/kextractor.c
> +        }
[fixed](https://github.com/paulgazz/kmax/pull/29/commits/a483e1dc177d1677b31c9d00639c0ee68e47a987)

2020-10-12 19:34 UTC, necipfazil commented on kmax/kclause
> +    # convert any "FOO" to CONFIG_FOO
You are right, this case is now handled by doing additional checks to see if the sym is declared ([here](https://github.com/paulgazz/kmax/pull/29/files#diff-8d62cac048e8a25600d27fadb8790cb1R385)). Also, to avoid having z3 complain about having a string constant instead of a boolean, the expressions are and'd with 1 [here](https://github.com/paulgazz/kmax/pull/29/files#diff-8d62cac048e8a25600d27fadb8790cb1R389), which should lead strings to evaluate to false.

2020-10-12 19:34 UTC, necipfazil commented on kmax/kclause
> +    convert_str_expr_dict_to_smt2 = lambda str_expr_dict : dict((fix_str_expr(k), convert_str_expr_to_smtlib2(v)) for k,v in str_expr_dict.items())
[fixed](https://github.com/paulgazz/kmax/pull/29/files#diff-8d62cac048e8a25600d27fadb8790cb1R385)

2020-10-13 04:37 UTC, paulgazz approved these changes

2020-10-13 04:37 UTC, merged