Update bugs-found.md
paulgazz/kmax pull request #55
Opened 2021-04-22 17:28 UTC by Uclydde

1. Add the corresponding patches to the existing commits.
2. Fix the dates on the existing commits.
2. Consolidate and remove duplicates.
3. Add one more recent commit.

2021-04-22 18:24 UTC, necipfazil commented
The commit link for `mips: fix unmet dependency for FRAME_POINTER when !ARCH_WANT_FRAME_POINTERS` seem to belong to a different fix.

Likewise, the patch link for `mips: fix unmet dependency for DEBUG_INFO when !DEBUG_KERNEL` seem to belong to a different one.

Could you fix these, and double-check the rest of the newly added ones?

Thanks!

2021-04-23 13:17 UTC, Uclydde commented
> The commit link for `mips: fix unmet dependency for FRAME_POINTER when !ARCH_WANT_FRAME_POINTERS` seem to belong to a different fix.
> Likewise, the patch link for `mips: fix unmet dependency for DEBUG_INFO when !DEBUG_KERNEL` seem to belong to a different one.

Good catch - these are fixed now.
> Could you fix these, and double-check the rest of the newly added ones?

Yep, there was a missing patch link as well. I added that in, too.

2021-04-23 14:56 UTC, necipfazil requested changes
Thanks for the fixes.

Seems like there are 2 more nits. Could you fix them?

Besides, LGTM

2021-04-23 14:56 UTC, necipfazil commented on docs/bugs_found.md
> +2021-03-29 [Commit](https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=7d37cb2c912dc5c25ffac784a4f9b98c06c6bd08): Committed into linux-next.
```suggestion
2021-04-09 [Commit](https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=7d37cb2c912dc5c25ffac784a4f9b98c06c6bd08): Committed into linux-next.
```

2021-04-23 14:56 UTC, necipfazil commented on docs/bugs_found.md
> +2021-03-06 [Commit](https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=7005227369079963d25fb2d5d736d0feb2c44cf6): Committed into linux stable.
Looks like a commit to linux-next (not linux stable).

This should be ` Committed into linux-next`, or the link should be to the stable tree if it's really the case.

2021-04-23 15:43 UTC, Uclydde commented on docs/bugs_found.md
> +2021-03-29 [Commit](https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=7d37cb2c912dc5c25ffac784a4f9b98c06c6bd08): Committed into linux-next.
Okay, I fixed those, and then added links for any linux-stable commits as well.

2021-04-23 19:41 UTC, necipfazil approved these changes

2021-04-24 17:16 UTC, paulgazz approved these changes

2021-04-26 20:52 UTC, merged